# Generated by Django 4.2 on 2023-05-08 13:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('realName', models.CharField(max_length=200)),
                ('birthDate', models.DateField()),
                ('info', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=254)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('audio', models.FileField(upload_to='audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])])),
                ('video', models.FileField(upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.artist')),
            ],
        ),
        migrations.CreateModel(
            name='PlayListSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.song')),
            ],
            options={
                'unique_together': {('playList', 'song')},
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(through='administracion.PlayListSong', to='administracion.song'),
        ),
        migrations.CreateModel(
            name='EventArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.artist')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.event')),
            ],
            options={
                'unique_together': {('event', 'artist')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='artists',
            field=models.ManyToManyField(through='administracion.EventArtist', to='administracion.artist'),
        ),
    ]
