# Generated by Django 4.1.7 on 2023-05-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_alter_playlist_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, default=None, through='administracion.PlayListSong', to='administracion.song'),
        ),
    ]
